name: Test
on: push

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install shellcheck
        run: sudo apt-get -y install shellcheck
      - name: Run shellcheck
        run: shellcheck *.sh test/*.sh test/*.bats
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install composer, bats
        run: sudo apt-get -y install composer bats jq python3-mwclient
      - name: Do pre-test set up
        run: sudo bash test/pre-setup.sh
      - name: Create the setup
        run: sudo bash setup.sh
      - name: Run smoke tests
        run: sudo bats test/tests.bats
